### ISSUE TITLE
焦点框错位

### ISSUE THREAD

**Issue by lph2012** [zhousuqiang/TvRecyclerView#1]
问题是这样的：我使用的是StaggerLayout，刚开始使用本地图片的时候，并没有问题，但是后来改用Glide动态加载图片之后，向右移动没有问题，当移动到最右边，然后往左边移动，移动到左边缘的时候，焦点框发生了错位，它获取到的坐标，是itemView之前的坐标。这种情况出现在使用Glide动态加载图片之后的。我重写了这个方法，稍微有改善：
![image](https://cloud.githubusercontent.com/assets/15904364/18306003/7fde1f90-751c-11e6-98ff-429a20365bb8.png)
请问有没有更好的办法？

**Comment by zhousuqiang** [comment]
如果使用的是移动边框，有可能会存在这种问题，你这种问题我还没有发现，但我发现了如果移动移动边框与TvRecyclerView外面使用了RelativeLayout布局的会就会出现类似你说的这种错位等奇葩问题。

**Comment by zhousuqiang** [comment]
1.0.6.4版本已修复此问题
