### ISSUE TITLE
有多种不同item布局时的问题

### ISSUE THREAD

**Issue by TimberBug** [zhousuqiang/TvRecyclerView#10]
如果有多中不同的item的布局，该怎么设置，adapter中的getItemLayoutId(int viewType)这个方法设置后不生效

**Comment by zhousuqiang** [comment]
请说具体一些,另外设置不同的布局应该是没有问题的.

**Comment by TimberBug** [comment]
不好意思，这个是我搞错了。。。
还有就是在多个布局时，不同布局中item之间的间距不一样，这个该怎么分别设置呢？

**Comment by zhousuqiang** [comment]
可以试试在不同布局中使用padding来控制间距

**Comment by TimberBug** [comment]
大佬，怎么使用padding来设置呢？尝试设置了几个地方不生效，可以在demo中实现这个功能不？谢谢
