### ISSUE TITLE
更新完数据后，item位置错乱

### ISSUE THREAD

**Issue by lph2012** [zhousuqiang/TvRecyclerView#2]
当我调用 mAdapter.notifyDataSetChanged();之后，显示的条目就发生了错位，有没有什么解决办法，我是这样使用的
![image](https://cloud.githubusercontent.com/assets/15904364/18374491/f8467b12-767f-11e6-8764-96fba33e2545.png)

**Comment by zhousuqiang** [comment]
有UI截图吗，我看下

**Comment by zhousuqiang** [comment]
@lph2012 问题已修复，请使用notifyItemRangeInserted进行更新数据，具体可以参考demo
