### ISSUE TITLE
demo中list界面在最右边刷新后无法继续移动到新的item项目

### ISSUE THREAD

**Issue by Witype** [zhousuqiang/TvRecyclerView#6]
打开DEMO->移动到最右边触发刷新操作->刷新完成后继续按右键盘->这个时候就无法移动了，需要按左一下然后才能继续向右滑动
Grid和其他的几个都是正常的。
我在自己的代码中调用
~~~
notifyItemRangeInserted
~~~
也是没用的，谢谢

**Comment by zhousuqiang** [comment]
可以加padding等方式尝试解决，根本原因是因为后面的item没有绘制出来导致的。
