### ISSUE TITLE
FocusBorder的问题

### ISSUE THREAD

**Issue by baixiaoY** [zhousuqiang/TvRecyclerView#7]
当recyclerview不是充满布局时，飞框是从整个布局顶部某个位置出现的，请问这是什么原因？

**Comment by zhousuqiang** [comment]
由于工作忙，回复晚了。
你说的是第一次移动焦点的情况吗，这是因为FocusBorder在初始化时view的初始化位置为0,0导致。如果对此有要求你可以尝试修改源码达到你想要的效果

**Comment by zhousuqiang** [comment]
https://github.com/zhousuqiang/TvFocusBorder
